[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "roboenv"
version = "0.1.0"
description = "COMP0245 Machine Learning for Robotics 26/27: Robotic simulation and control environment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pybullet",
    "pin",
    "robot-descriptions",
    "casadi",
    "matplotlib",
    "scipy",
    "osqp"
]

[project.scripts]
test-cartesian-kin = "tests.cartesian_kinematic_controller:main"
test-cartesian-impedance = "tests.cartesian_impedance_controller:main"
test-humanoid-walk = "tests.humanoid_walk_controller:main"
test-mobile-base-kin = "tests.mobile_base_kinematic_controller:main"
test-mobile-base-arm-kin = "tests.mobile_base_arm_kinematic_controller:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-dir]
"" = "."
simulation_and_control = "simulation_and_control/simulation_and_control"
tests = "tests"

[tool.setuptools.packages.find]
where = ["simulation_and_control", "."]
include = [
    "simulation_and_control",
    "simulation_and_control.*",
    "tests",
    "tests.*",
    "configs",
    "configs.*",
    "models",
    "models.*",
]
exclude = [
    "simulation_and_control.simulation_and_control",
    "simulation_and_control.simulation_and_control.*",
]
namespaces = true

[tool.setuptools.package-data]
"*" = ["*"]